before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
language: node_js
node_js:
- 6.2.1
cache:
  directories:
  - node_modules
  - bower_components
install:
- npm install -g typescript
- npm install -g typings
- npm install -g karma-cli
- npm install -g protractor
- npm install -g angular-cli
- npm install
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Hus7cVoH/SVz3TmurP84z1Vvlw9+/zL6Oi6Az+OPGvGF4+OOvSGNE8nxZjd2fyd1auL8NYIMhtvZS0EN7VWXPL8EDHMI4vGzGYzrv2mGoJaxFiS2QzFRMY0s2a80+uCRl93WwVt6XmsrUhuTADOa87KC9V7NYBzUnbGHxd32bMi4HRHY8kqgtSf2Rf6Dq/h+W+kJ7H4uGtfLod6DZAgv6cDMAAf4gLfYAL+kjZAiRNF4H2aXddP5/wjv5XjslXXFEHoHFiv+ZnxGsDl4l1nontV7utg/6jNQyquobWzkg/95hZMCtBStzvWuy29BlytrFDE3DcxI8C6t6YgVLTCLTvECbaAz/B2CDZjsdm0WmdYGs2RHp/DQtsrkca3ftuRAd00x5C+Cxqt4C4NgJ9yKVus3M4hKJcytwW+frKQIFGuI4w8iCCMLgmRHldZN5IlNQXf7bnqWoJG0g35zQHHcey88mOdRDY+LQlyOEQVvdp2bVtUJ6EEhqVkHGBOSNjxosNJ1kKobX0ThIWnPiEHDl9Ro6FqXG9a1nXL38qB3lP3XlApNAQOktbXdXPLi+M1QlMKXs4dkwVPsJpKygildpAirL33pqGhb3b5jHyVTpy+NznXGCT+6ilHuKnY5LrT+9go9Wiemdi9g7LwxV1Ih131WocDpDvkZz1qx8AfZ8WY=
  app: food-delivery-kunal
  on:
    repo: kmathur7/food-app
