before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

language: node_js
node_js:
  - "6.2.1"

cache:
  directories:
    - node_modules
    - bower_components

install:
- npm install -g typescript
- npm install -g typings
- npm install -g karma-cli
- npm install -g protractor
- npm install -g angular-cli
- npm install